# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def use_pods
    pod 'CHTCollectionViewWaterfallLayout/Swift'
end

target 'Houz' do
    use_pods
end
