# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def use_pods
    pod 'CHTCollectionViewWaterfallLayout/Swift'
    pod 'NVActivityIndicatorView'
    pod 'Hero'
    pod 'Koloda', '~> 4.3.1'
    pod 'XLPagerTabStrip', '~> 8.0'
    pod 'Kingfisher'
    pod 'MMPlayerView', '~> 3.1.3'
    pod 'Gallery'
    pod 'Lightbox'
    pod 'Toast-Swift'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
end

target 'Houz' do
    use_pods
end
